// This file was automatically generated from schema.json
// Do not edit this file directly

/**
 * @minItems 1
 */
export type SchemaData = [LessonData, ...LessonData[]];
export type LessonData = {
  [k: string]: unknown;
} & {
  id: string;
  name: string;
  /**
   * @minItems 1
   */
  templates: [ExerciseTemplateData, ...ExerciseTemplateData[]];
  [k: string]: unknown;
} & {
  id: string;
  name: string;
  /**
   * @minItems 1
   */
  templates: [ExerciseTemplateData, ...ExerciseTemplateData[]];
  [k: string]: unknown;
};

export interface ExerciseTemplateData {
  id: string;
  instruction: string;
  exerciseType: ExerciseType;
  generator: Generator;
  data?: {
    [k: string]: unknown;
  };
  blockedBy?: string[];
  [k: string]: unknown;
}
export interface ExerciseType {
  name: 'BY_INSTRUCTION';
  data?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Generator {
  name: 'SINGLE' | 'VARY_PROPERTY_WHOLE_NUMBER_RANGE';
  data?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
